### ISSUE TITLE
Reconstruction failed

### ISSUE THREAD

**Issue by Sinapzy** [ufo-kit/tofu#101]
Hello, the version I installed is the latest version，But when I use the command line or GUI to rebuild, the problem is as follows.
- use the command line
![commind_erro](https://user-images.githubusercontent.com/45203805/83494888-7f66cc00-a4e9-11ea-842a-226b5afe40da.jpg)
- use the GUI
![GUI_ERROR](https://user-images.githubusercontent.com/45203805/83494991-ade4a700-a4e9-11ea-8a30-832b948063a8.jpg)

How can i solve this problem?Thank you.

**Comment by tfarago** [comment]
`--axis-pos` is not an argument for `tofu tomo`, it's just `--axis`. Please take a look at `tofu tomo --help` to see other arguments. Does it work now?

**Comment by Sinapzy** [comment]
Thanks,the problem has been solved.
