### ISSUE TITLE
Do you plan to support the PyQt4 ?

### ISSUE THREAD

**Issue by huyuhuster** [ufo-kit/tofu#105]
https://github.com/ufo-kit/tofu/blob/164117cbef0eddfc777963132587bff45eeca404/tofu/gui.py#L16

**Comment by tfarago** [comment]
`tofu gui` is currently not being developed and will be superseded by [tofu flow](https://github.com/ufo-kit/tofu/pull/103) soon. BTW, did you mean if we planned to support PyQt**5**? Have you perhaps tried to change to PyQt5 yourself? The way I see it it shouldn't be too much work. If you are not familiar with PyQt we will try to take care of this in case `tofu flow` won't suit your needs.

**Comment by huyuhuster** [comment]
Yes, I mean PyQt5, sorry. So when will you release the tofu flow?

**Comment by tfarago** [comment]
Unofficially you can already use it, it's here as pull request #103 . I am hoping for an official release in December, but at this point I cannot promise it, sorry.

**Comment by tfarago** [comment]
Done long time ago...
