### ISSUE TITLE
INFO:Couldn't determine image dimensions 

### ISSUE THREAD

**Issue by Sinapzy** [ufo-kit/tofu#106]
I have the following problem when using the command line
the exmple size of input images is 1024*1024 pixels
- My command line:
#tofu preprocess --projections pro/ --output pr/projPR-%04i.tif-fix-nan-and-inf --energy 18 --propagation-distance 0.5 --pixel-size 2.5e-6 --regularization-rate 5 --retrieval-padded-height 1024 --retrieval-padded-width 1024 --projection-filter none
- My ERROR:
INFO:Couldn't determine image dimensions from 'pro/tomo_0000.tif'
ERROR:Could not determine width from input

**Comment by tfarago** [comment]
Open python console and check what this tells you please:
```python
from tifffile import TiffFile
with TiffFile(filename) as tif:
    page = tif.pages[0]
    shape = (page.imagelength, page.imagewidth)
    if len(tif.pages) > 1:
        shape = (len(tif.pages),) + shape
```

**Comment by tfarago** [comment]
where you exchange `filename` for `pro/tomo_0000.tif`
