### ISSUE TITLE
Improve default padding (suggestion)

### ISSUE THREAD

**Issue by sgasilov** [ufo-kit/tofu#110]
Hello,

please consider changing lines 128, 129 in https://github.com/ufo-kit/tofu/blob/master/tofu/preprocess.py
    default_padded_width = next_power_of_two(width)
    default_padded_height = next_power_of_two(height)
to 
    default_padded_width = next_power_of_two(width+50)
    default_padded_height = next_power_of_two(height+50)

In this case padding with default arguments will work without boundary artifacts for sensors with 2048 pixels (there are many) or, in general case, if input images have been cropped to width/height which is very close but slightly smaller than the powers of two.

Best,
Sergei.

**Comment by tfarago** [comment]
I'd say `next_power_of_two(width * 2)` in order to completely remove convolution outliers, like [here](https://github.com/ufo-kit/tofu/blob/master/tofu/util.py#L219). Do you agree?

**Comment by sgasilov** [comment]
If you are completely sure that you have to double the size of the images to avoid the artifacts than yes. 

The reason I'm cautious are those problems with running out of VRAM on a workstation with NoMachine, or any other processes consuming a small fraction of VRAM in general case. After experiencing these problems, I'd say that unless absolutely important it is better to avoid unnecessarily large images. E.g. for PCO Edge 5, padding to 4096 pixels will be more than enough in every imaginable situation, but if you double it before padding to the next power of 2, the image in VRAM will occupy ~20 (!) times more memory than the original image on disk.

**Comment by tfarago** [comment]
Good points, done.
