### ISSUE TITLE
Rang and list issues in the new python(3.9)

### ISSUE THREAD

**Issue by huyuhuster** [ufo-kit/tofu#111]
https://github.com/ufo-kit/tofu/blob/63d4cf9d1258d4af95a8700656db703764a6f693/tofu/preprocess.py#L235
Dear  administrator,
      When I use tofu in python 3.9, I got the error TypeError: unsupported operand type(s) for +: 'range' and 'list'.

**Comment by tfarago** [comment]
That's because the Python 3 transition hasn't happened yet, but it will soon, just keep an eye on #100 please.
