### ISSUE TITLE
What is the license for tofu?

### ISSUE THREAD

**Issue by codehelp** [ufo-kit/tofu#116]
No license is set for tofu at the moment - nothing in GitHub, or in setup.py and no LICENSE file.
Without a license, users have no permission from the creators of the software to use, modify, or share the software - it is effectively proprietary.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Please choose a license and add the license text to GitHub. Thank you.

**Comment by tfarago** [comment]
Thanks for the hint, fixed with 8ac183f853daa34765e59cc98956eff666173370.
