### ISSUE TITLE
ValueError: Namespace Ufo not available

### ISSUE THREAD

**Issue by dengtijian** [ufo-kit/tofu#117]
After I installed tofu, command "tofu --version" or "tofu tomo -h" will show the following:
..................................................................................................................................................................................................
Traceback (most recent call last):
  File "/usr/local/bin/tofu", line 4, in <module>
    __import__('pkg_resources').run_script('tofu==0.11.0', 'tofu')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/tofu-0.11.0-py3.8.egg/EGG-INFO/scripts/tofu", line 12, in <module>
    gi.require_version('Ufo', '0.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Ufo not available

**Comment by tfarago** [comment]
If you are on Ubuntu 20.04, you can just copy-paste [these](https://github.com/ufo-kit/ufo-core/blob/master/docker/Dockerfile.nvidia.ubuntu-20.04#L48-L50) lines in your terminal.

**Comment by dengtijian** [comment]
> If you are on Ubuntu 20.04, you can just copy-paste [these](https://github.com/ufo-kit/ufo-core/blob/master/docker/Dockerfile.nvidia.ubuntu-20.04#L48-L50) lines in your terminal. But you need to change `ENV` for `export` and use `=`, like this:
> 
> ```shell
> export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
> export GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0:$GI_TYPELIB_PATH
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
> ```

It did work. Thanks a lot!
"tofu --version", "tofu tomo -h" or "tofu estimate --projections 0-180" are both ok, 
but error occurs when excuting command "tofu flatcorrect  --projections tomo/ --flats flats/ --flats2 flats2/ --darks darks/ --output tomocorr/proj_%05i.tif --absorptivity --fix-nan-and-inf --output-bytes-per-file 0" and "tofu tomo --sinograms sinocorr/ --output sli/sli_%05i.tif --axis 1100.0 --output-bytes-per-file 0"

 ERROR: ufo-resource-resources-error-quark: OpenCL Error: Invalid error code (0)

if the "ERROR" message is because that CUDA doesn't work.

I have tried to install CUDA in WSL2 Ubuntu 20.04, but error is still not solved.

So, I want to know how to  set CPU's integrated graphic card for getting ufo work as you said here. https://github.com/ufo-kit/ufo-filters/issues/220#issuecomment-1102686297

**Comment by tfarago** [comment]
I described it in a short way and provide a link to a more detailed description [here](https://ufo-core.readthedocs.io/en/latest/install/windows.html).

**Comment by dengtijian** [comment]
> I described it in a short way and provide a link to a more detailed description [here](https://ufo-core.readthedocs.io/en/latest/install/windows.html).

ok, I will have a try.
