### ISSUE TITLE
tofu flow Qt float issue

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/tofu#130]
In PyQt 5.15+ the GUI doesn't work because at many places of the qtpynodeeditor, Qt complains that it can't use `float` as argument and needs `int`. @MarcusZuber do you know a quick fix for this or do I need to make a PR for the editor?

**Comment by MarcusZuber** [comment]
Not the most elegant way, but could you try to set `typing.TYPE_CHECKING` to `False`.
This yould also help `PyQt5.sip.enableoverflowchecking(False)()`.

**Comment by tfarago** [comment]
First didn't help and second doesn't know about sip...

**Comment by tfarago** [comment]
For Python3.9+ one needs to install qtpynodeeditor==0.3.0
