### ISSUE TITLE
logarithmic reconstruction

### ISSUE THREAD

**Issue by ThomasvdK** [ufo-kit/tofu#35]
Hi,

I recently tried a ffb and noticed a lacking option for logarithmic reconstruction.
Would you add the feature to the gui?

Many thanks and best wishes
Thomas

**Comment by matze** [comment]
You mean taking the logarithm of the raw projection data without computing a flat-field correction?

**Comment by ThomasvdK** [comment]
No, I mean taking the negative logarithm (base e) of the flat- and dark field-corrected projections.

**Comment by matze** [comment]
That should be possible with the "Use absorptivity" option:

![ffc](https://cloud.githubusercontent.com/assets/115270/7813476/cbbd1f7a-03bb-11e5-9e2e-55e2b42b9acd.png)

**Comment by ThomasvdK** [comment]
I just tried, but it had no effect: /mnt/LSDF/tomo/ufo-reco/Onthophilus_striatus_EtOH_05/reco_test
(See the reconstruction from the sinograms for comparison).

**Comment by matze** [comment]
On which machine are you reconstructing? On mine it does what it's supposed to be, so I guess there might be something not up-to-date.

**Comment by ThomasvdK** [comment]
Reconstruction was done with anka-nc-gpu1.

**Comment by matze** [comment]
Looks like the software on the number cruncher is outdated. The openSUSE installation on the new ufosrv2 seems to work fine.

@tfarago: could you please update the number cruncher?

**Comment by tfarago** [comment]
will do and close this when fixed

**Comment by tfarago** [comment]
I just tried to reconstruct there and it works as expected. The version we have there is actually quite recent so the update is not necessary. I will contact the users individually and help them to set the parameters so that it works.
