### ISSUE TITLE
We need to specify the file patterns

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/tofu#49]
When a user does _--input darks/*.tif_ it doesn't work, it has to be specified like this _--input "darks/*.tif"_ Is this already somewhere documented? Also, we should write what patterns are accepted exactly.

**Comment by matze** [comment]
In my opinion, this is a WONTFIX because the former is expanded by the shell while the latter parameter is passed verbatim to the process. This "problem" affects all command line programs not only ours.

**Comment by matze** [comment]
To add to my previous comment: one does not even need to specify a file pattern at all, just the directory should be enough. Thus, I'll close this.
