### ISSUE TITLE
Reconstruction Doesn't Work

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/tofu#51]
When I run e.g.:
`ufo-reconstruct tomo --input sino.tif --axis 668 --output slice.tif`

I get:
```bash
(process:22532): Ufo-WARNING **: The given address has invalid format. (Expecting "<protocol>://<address | device>:<port>")

(process:22532): Ufo-CRITICAL **: ufo_remote_node_send_json: assertion 'UFO_IS_REMOTE_NODE (node)' failed

(process:22532): Ufo-CRITICAL **: ufo_task_node_set_proc_node: assertion 'UFO_IS_TASK_NODE (task_node) && UFO_IS_NODE (proc_node)' failed
**
Ufo:ERROR:/ka/ka_ips/ka_jd2392/dev/ufo-core/ufo/ufo-remote-task.c:68:ufo_remote_task_setup: assertion failed: (priv->remote != NULL)
Aborted
```

On ufo2 server and also the number crunchers. Could you check it out please?

**Comment by matze** [comment]
Everything up-to-date? This works for me and ufo2. By the way I suspect that an existing `reco.conf` contains a garbled entry for the remote address list.

**Comment by tfarago** [comment]
Thanks for the reco.conf suggestion. ufo2 works for me now. gpu4 is down because LSDF is down, I will check it later and close this if it's fine there.

**Comment by tfarago** [comment]
yep.
