### ISSUE TITLE
tofu init: create configuration file with the user specified name

### ISSUE THREAD

**Issue by VeneraW** [ufo-kit/tofu#57]
tofu init gives a chance to specify output path for storing the slices but it is not possible to store in this folder the config file itself or give to it designed name, such as sampleA.conf 
The would be great feature if one needs afterwards to look through all conf files in figure out what went wrong and in which experiment

**Comment by matze** [comment]
Giving a name other than `reco.conf` should be possible with

    $ tofu init --config foo.conf

Storing it in the (not-yet-existing) output folder could be made possible if really required (or done manually before hand using `mkdir`).

**Comment by VeneraW** [comment]
Well, if I am typing tofu init --config foo.conf, it actually gives an EROOR: recon.conf already axists
As a result it does not create a conf file. One can specify whatever name but it won't be taken.
