### ISSUE TITLE
tofu sinos: reconstructing sinograms from data acquired over 360 degress rotation

### ISSUE THREAD

**Issue by VeneraW** [ufo-kit/tofu#58]
tofu sinos does work only with the data acquired over 180 degrees rotation, for reconstructing data from 360 degrees rotation, one need to take or half of the acquired projections or use tofu lamino. It is a bug

**Comment by matze** [comment]
You could set `--angle` to 0.01745329 which should allow reconstructing 360 degree data. Or do you mean you want to reconstruct 180 degree data partially from the full scan?

**Comment by VeneraW** [comment]
No I mean reconstructing data from 360 degrees acquisition and yes Tomas suggestion was also to specify angle between projections -  it does not work.

**Comment by tfarago** [comment]
Great, I see this tracker is starting to serve it's purpose. Now to the issue itself. I will take a look at this with your data again.

**Comment by tfarago** [comment]
I just tried this command
```bash
tofu tomo --sinograms sino_1000.tif --axis 1260 --output slice.tif --angle 0.006270644019141304
```
and it gave me a reasonably-looking slice. There are 1002 projections, so the angle in the command is 2Pi/1002.

**Comment by VeneraW** [comment]
Hey,

just wanted to let you know that in the end it actually worked :D thanks a lot...using it for my data now
