### ISSUE TITLE
Fix reco.conf feature

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/tofu#64]
Hi guys, 

as discussed with Tomas, I report the that reco.conf feature is very inconvenient right now. I do not mind than ufo stores last set of parameters that was used, I do not like that it tries to use them if the file exists in the directory. I suggest either to completely disable it or to add a flag/parameter in tofu script, which ignores reco.conf by default and only when active, will tell tofu to use parameters from the log file instead of those provided in the command line.

Thanks,
Sergei

**Comment by tfarago** [comment]
Thanks for creating an issue! We will fix it.
