### ISSUE TITLE
provide more flexibility in flat-field-correct

### ISSUE THREAD

**Issue by lucito** [ufo-kit/tofu#67]
Hi,
it would be great to have even four arguments, the projection stream, the darks, the references, and a second set of darks for the references (in case you use different exposure times, for example). If you have only the first two, you do dark-field correction, if you have three, you do the standard flat-field correction as it is now, and if you have four, you use that latter ones for substraction from the beam reference images.
Have a nice day,
L

**Comment by lucito** [comment]
This applies to ufo-launch, tofu flatcorrect and tofu preprocess.

**Comment by milkdrop** [comment]
Hello, Lucito, 

Could you make a real life example when someone will actually need such functionality? If you need it for you testing or developing purposes then a very quick way to get around this is to generate two dummy files: one "flat" with all ones and one "dark" with all zeros with the same dimensions as the data set. Then use on of those in you flatcorrect procedure to achieve what you are asking for. It takes less than a minute to do this with ipython. 

To developers: the reason I replied to this post is that implementing such functionality only makes the source code more complicated without any real justification. Indeed in practice not a single user will need partially corrected flat-fields, while an interested person can easily simulate this case without making unnecessary corrections in the source code. 


Cheers,
SErgei

**Comment by lucito** [comment]
Hi Sergei,
a real life example is when I do laminography (or local tomography where the sample covers the entire field of view of the detector) and I want to expose the beam reference images less in order to avoid saturation. I do that regularly with my data. Dark current compensation is so widespread that it can be considered more fundamental than flat-field correction. We may discuss of course, if a module called "flat-field correct" needs to accomodate it. But since it does not modify the default behaviour, I would say yes....
At the moment I am using octave to make me a images with ones, for instance. But the division by one will still be carried out....
Best wishes,
L

**Comment by tfarago** [comment]
Such complex pre-processing should be carrier out separately, the default pipelines should stay rather simple, and now we have the flat multiplier, I think it's a good compromise.
