### ISSUE TITLE
Optimize search of the rotation axis

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/tofu#70]
Hello again ))

a suggestion of a small feature to enhance the performance of your tofu gui, "center of rotation" tab:
it would be great if in the second tab you can when you brows for 0 and 180 degree projections you could have an option to load the raw projections and apply the flatfield correction to it.

Benefit: fastest "standard operation procedure" for reconstruction: (1) check the rotation axis (you only need to apply flat field correction to two views) and then (2) execute tofu tomo --projection --flats --darks --axis    

Currently I suggest users to use a small python macro which does flatfield correction of the first and last views and then load those two files in the tofu gui, but seemingly this feature can be also very easily integrated into tofu gui "center of rotation" tab. 

Cheers,
Sergei.

**Comment by tfarago** [comment]
Good point, thanks.

**Comment by matze** [comment]
I added a [change](https://github.com/ufo-kit/tofu/commit/a0a9da38bbbbc3a4df4fef91618c9b702f0192bf) that will do flat-field correction on the two projections if enabled. One caveat though: I do this "by hand" at the moment and not using the pipeline as set up for the reconstruction stage, so parameters like median filtering won't apply. This needs to be refactored so, we can re-use those pipelines for "side jobs".

**Comment by milkdrop** [comment]
thank you very much, this patch works perfectly fine for me!
