### ISSUE TITLE
very confused: absorptivity is always True

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/tofu#71]
Hallo, 

while testing the preprocessing_pipeline today I have noticed that absorptivity parameter is always True. So I rolled back to the tofu version which I downloaded in November (which does not even has preprocessing part in preprocess.py) and exactly the same thing happens in flatcorrect the -log is always taken. So I played a bit with settings of absoprtivity parameter in config.py. Achieved nothing it is always True. The only way I managed to switch it of is to pass False directly to the 'flat-field-correct' task. 

Could you comment on this? Is it some particular behavior of my python distribution or because I do not know how to use python argparser properly? 

Here I print the value of absorptivity as it appears in create_flatcorrect_pipeline
apple_Al>tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif
True
apple_Al>tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif --absorptivity
True
apple_Al>tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif --absorptivity False
True
apple_Al>tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif --absorptivity 0
True

**Comment by tfarago** [comment]
Can you pull the recent master? For me the first command looks fine, i.e. no absorptivity.

**Comment by milkdrop** [comment]
Well, this is tofu which I downloaded yesterday using link to the zip archive. But as I described, the same applies to the November release. Anyways, direct answer to your question:
sudo git clone https://github.com/ufo-kit/tofu.git
sudo python setup.py install --record install_manifest.txt
tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif
returns zero image for all ones flat.tif and all zeros dark.tif

**Comment by tfarago** [comment]
I am sorry I meant _works_ instead of _looks_. I tried it with correct result. Please run it with `--verbose` and post the output.

**Comment by milkdrop** [comment]
Hello! 
tofu installed yesterday using git clone:
tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif --verbose
DEBUG: General
DEBUG:   config           reco.conf
DEBUG:   log              -
DEBUG:   output           fu.tif
DEBUG:   output_bitdepth  32
DEBUG:   output_maximum   -
DEBUG:   output_minimum   -
DEBUG:   verbose          True
DEBUG:   width            -
DEBUG: Input
DEBUG:   bitdepth         32
DEBUG:   height           -
DEBUG:   number           -
DEBUG:   resize           -
DEBUG:   retries          0
DEBUG:   retry_timeout    0
DEBUG:   start            0
DEBUG:   step             1
DEBUG:   y                0
DEBUG:   y_step           1
DEBUG: Flat field correction
DEBUG:   absorptivity     True
DEBUG:   dark_scale       1.0
DEBUG:   darks            dark.tif
DEBUG:   fix_nan_and_inf  True
DEBUG:   flats            flat.tif
DEBUG:   flats2           -
DEBUG:   projections      flat.tif
DEBUG:   reduction_mode   Average
DEBUG: Setting read:start to 0
DEBUG: Setting read:step to 1
DEBUG: Setting read:y to 0
DEBUG: Setting read:y_step to 1
DEBUG: Setting read:y to 0
DEBUG: Setting read:y_step to 1
DEBUG: Setting read:y to 0
DEBUG: Setting read:y_step to 1
DEBUG: Doing flat field correction using reduction mode `average'

**Comment by milkdrop** [comment]
just tried to remove everything completely  xargs rm < install_manifest.txt and reinstall - same results. Incidentally, I remember now that Lisa has noticed that git clone did not copied the latest master in one case (about two weeks ago). Do not know if it can be relevant at all, just an observation. 

Cheers!
SErg

**Comment by ldorofeeva** [comment]
No, dude, it was when I forked ufo-filters

**Comment by milkdrop** [comment]
Well, was playing with verbose parameter and if I call tomo directly all is well. Still confused, need help -)! Is it possible that it is not that I'm wrong, but default values in config.py and "if" statements in preprocess.py used in creating of pipelines are conflicting in some way? 

Battery-Dyn>ax=1049; for i in *; do tofu tomo --flats $i/Flat --darks $i/Dark --projections $i/Tomo --output $i/Slices-test/proj-0000.tif --axis $ax --fix nan-and-inf --verbose --y 500 --height 1; (( ax+=2 )); done
DEBUG: General
DEBUG:   config           reco.conf
DEBUG:   log              -
DEBUG:   output           Repeat_0SOC/Slices-test/proj-0000.tif
DEBUG:   output_bitdepth  32
DEBUG:   output_maximum   -
DEBUG:   output_minimum   -
DEBUG:   verbose          True
DEBUG:   width            -
DEBUG: Input
DEBUG:   bitdepth         32
DEBUG:   height           1
DEBUG:   number           -
DEBUG:   resize           -
DEBUG:   retries          0
DEBUG:   retry_timeout    0
DEBUG:   start            0
DEBUG:   step             1
DEBUG:   y                500
DEBUG:   y_step           1
DEBUG: Flat field correction
DEBUG:   absorptivity     False
......

**Comment by tfarago** [comment]
From the output of the verbose flag it seems to me that you are using an older version of tofu, Can you go to the directory where tofu is installed and post the result of this command `git log --oneline --max-count 1` please?

**Comment by tfarago** [comment]
If it isn't `a0a9da3 Do flat field correction before center estimation` uninstall tofu please (with the xargs rm command), then type tofu and if you don't get an error message about missing program tofu it means that you have an installation hanging around which shouldn't be there and you need to get rid of that first.

**Comment by tfarago** [comment]
Get back to me once you have done that and we will pick up from there,

**Comment by milkdrop** [comment]
Season’s Greetings! 

tofu>git log --oneline --max-count 1   prints exactly 
a0a9da3 Do flat field correction before center estimation.

which does not show any other tofu programs when tofu is uninstalled. After it has been reinstalled  the absorptivity is still "True" for tofu flatcorrect --projections flat.tif --flats flat.tif --darks dark.tif --output fu.tif --verbose

**Comment by tfarago** [comment]
Oh man,, this is getting a bit difficult to debug... Do you by any chance have a reco.conf in the directory from which you are trying to run it?
Another thing to check: can you start python and type
```python
import tofu
tofu.__file__
```
please? Is the result pointing to the tofu installation printed in the install_manifest.txt file?

**Comment by milkdrop** [comment]
Problem was found today with the help of Tomas - it is currently impossible to overwrite absorptivity value stored in the reco.conf file.

**Comment by matze** [comment]
But this issue may stay open until the actual problem is resolved.

**Comment by tfarago** [comment]
The actual problem has been shifted to #72
