### ISSUE TITLE
seg fault !

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/tofu#74]
Hello, 

I report the problem in tofu section because that is where it appears. Call to reconstruct in tofu gui produces errors: 
per each slice:
(process:5548): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-core-0.1    5.0/ufo/ufo-buffer.c:420>: CL_INVALID_EVENT
concludes with:
FFT program build log on device Quadro 4000
FFT program build log on device Quadro 4000
(process:5548): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-filters-    0.15.0/src/ufo-fft-task.c:131>: CL_INVALID_PROGRAM_EXECUTABLE
Segmentation fault (core dumped)

Note that: center of rotation tab works perfectly fine for the same data set, same settings.

Now, the interesting part: reconstruction can be done successfully by using direct call to tofu tomo: 
tofu tomo --projections tomo/ --axis 1531 --y 100 --height 1 --output ../../sergei/slice-test.tif --darks dark/ --flats flat/ --absorptivity --fix-nan-and-inf
works as it should
however 
tofu tomo --projections tomo/ --axis 1531 --output ../../sergei/slice-test.tif --darks dark/ --flats flat/ --absorptivity --fix-nan-and-inf
causes massive spam of errors (per each slice I presume):
(process:5741): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-core-0.15.0/ufo/ufo-buffer.c:420>: CL_INVALID_EVENT
and ends with 
FFT program build log on device Quadro 4000
FFT program build log on device Quadro 4000
(process:5741): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-filters-0.15.0/src/ufo-fft-task.c:131>: CL_INVALID_PROGRAM_EXECUTABLE
Segmentation fault (core dumped)

**Comment by tfarago** [comment]
Can you check the command which segfaults with plain ufo-launch? I wonder if this is related to the segfault problem in preprocess mentioned in #72.

**Comment by milkdrop** [comment]
Hi Tomas,, well that was my first thought that they are related. Well to your question - I've tested 'ffc' through ufo-launch and tofu flatcorrect - both work!!! but print errors!! (see output below).  Unfortunately I do not have time to look up how to call tomography from ufo-launch so I cannot compare the next step. 
Also, to give you all details: tofu gui actually saved files without seg fault, but files were corrupted - I'll send you an example by email. 

tofu flatcorrect --projections tomo/ --output ../../sergei/test4/foo-%04i.tif --darks dark/ --flats flat/ --absorptivity --fix-nan-and-inf
(process:8240): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-core-0.15.0/ufo/ufo-buffer.c:457>: CL_OUT_OF_RESOURCES

ufo-launch [read path=tomo, read path=dark, read path=flat] ! flat-field-correct ! write filename="../../sergei/test1/foo-%04i.tif"
.......
(ufo-launch:8080): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-core-0.15.0/ufo/ufo-buffer.c:395>: CL_OUT_OF_RESOURCES
3000 items processed ...
(ufo-launch:8080): ocl-CRITICAL **: Error </home/abuild/rpmbuild/BUILD/ufo-core-0.15.0/ufo/ufo-buffer.c:457>: CL_OUT_OF_RESOURCES
3001 items processed ...
Finished in 8.63152s

**Comment by matze** [comment]
If this was not a problem before I doubt this has something to do with our software, standard flat-field correction and reconstruction are pretty straightforward and should not be affected by #72. Some questions: did you update drivers? Is it a larger data set than before? Is the GPU working correctly with other software?

**Comment by milkdrop** [comment]
Hello, 

No errors indeed after I've compiled source and then installed rather than yum.
