### ISSUE TITLE
Just turn off reco.conf functionality please

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/tofu#75]
Hi guys, 

reco.conf is still causing more troubles and brings virtually nothing good. I've started to face another problem with write permission whn I decided to completely separate raw data from reconstructed. I presume that there is no exception handling in this part of the code and if user wants to reconstruct data (or simply find axis of rotation) and launches tofu gui in the folder where he/she does not have write permissions then even Ctrl+C does not help. 

In addition to this the old problem with default flags has not been yet resolved. 

Please fix it in any way you find appropriate. This reco.conf  makes a lot of mess when you try to show how to use ufo to people who do not even have very good idea about difference in absolute and relative paths.

**Comment by xeiwoka** [comment]
Hi to everybody,


and how about a --ini flag with the filename behind it in case one would need it?

With kind regards,
L

________________________________

**Comment by tfarago** [comment]
Yeah that could work, because now the command line subcommands, like `reco` don't save anything. In GUI there is the "save as" option, which is enough I guess. Should I add this flag?
