### ISSUE TITLE
Enhancement: add flat-field multiplier 

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/tofu#85]
Hello, 

in case of local CT and strongly absorbing samples it is often beneficial to use larger exposure time for projections in order to improve signal to noise ratio. Flat fields are acquired as usual in such a way as not to saturate the detector. To make flat field correction properly one would need to multiply flat by an appropriate factor, almost like darks multiplier for ESRF files. Can we add it as an optional parameter? Lisa has volunteered to do that, one question for Tomas though: what is place is better to do it - at lower level in ffc filter or at higher level in tofu preprocess?

Regards,
Sergei.

**Comment by tfarago** [comment]
To keep things consistent she could add a "flat-scale" property to the ffc task in filters and adjust tofu accordingly.

**Comment by milkdrop** [comment]
@ lucito - Also, although it is generally true that separate darks should be acquired for different exposure times, it can be totally neglected in practice because exposure times are small, counts are high, modern sCMOS cameras have like 0.5 e-/sec for dark current so difference between 10 ms and 100 ms is vanishingly small (<1 count), while all modern, good CCDs have super low dark current in general. 

@ Tomas - Lisa has simply inserted "evaluate expression" in the create_flat_correct_pipeline of preprocess.py and it works perfectly fine, but she says she is going to add this parameter directly to the ffc filter.

**Comment by lucito** [comment]
@ milkdrop - My take to things occuring in practise is: you never know. One day you may want to expose for longer than some tens of seconds. It happened to me already...
