### ISSUE TITLE
confused: reconstructed image weired

### ISSUE THREAD

**Issue by demonlj** [ufo-kit/tofu#89]
ubuntu 19.04
nvidia mx250
cuda 10.1
micro-ct: cone beam skyscan 1176

scan log as below:
```
[System]
Scanner=SkyScan1176
Instrument S/N=10B08010
Hardware version=A
Software=Version 1. 1 (build 12)
Home directory=C:\SkyScan1176
Source Type=PANalytical's Microfocus Tube
Camera=Princeton Instruments 
Camera Pixel Size (um)=   12.49
CameraXYRatio=1.0030
Bed shift in X per 1000 lines=-3.976000
Bed shift in Y per 1000 lines=-1.983000
[Acquisition]
Filename Prefix=1
Filename Index Length=4
Number of Files=  515
Source Voltage (kV)=  65
Source Current (uA)= 385
Number of Rows= 1336
Number of Columns= 2000
Image crop origin X=   0
Image crop origin Y=0
Camera binning=2x2
Image Rotation=0.9900
Gantry direction=CW
Number of connected scans=1
Image Pixel Size (um)=   17.51
Object to Source (mm)=120.000
Camera to Source (mm)=165.000
System Matrix Calibration=NO
Vertical Object Position (mm)=-82.500
Optical Axis (line)= 660
Filter=Al 1mm
Image Format=TIFF
Data Offset (bytes)= 264
Horizontal overlap (pixel)=64
Camera horizontal position=Center
Depth (bits)=16
Visual Camera=OFF
Synchronised Scan=OFF
Delay for external event (ms)=(5)
List mode=OFF (2)
Screen LUT=0
Exposure (ms)=   300
Rotation Step (deg)=0.700
Frame Averaging=OFF (1)
Use 360 Rotation=YES
Geometrical Correction=ON
Camera Offset=OFF
Scanning Start Angle=360.000
Median Filtering=ON
Flat Field Correction=ON
Rotation Direction=CC
Scanning Trajectory=ROUND
User Name=
User Rights=full access
Type Of Motion=STEP AND SHOOT
Source Temperature=31.47 �C
Study Date and Time=Aug 05, 2019  22:46:08
Scan duration=00:08:48

```

as there are 515 tifs in total, angle_step = 0.7, so I set the 0° image as 10000.tif, and 180° image as 10258.tif 

> 180/0.7 ≈ 258

using `tofu gui`  to find the center,  using 0° image ([10000.tif](http://demonlj.f3322.net:8588/s/GeBDyQcg55Z39mE)) and 180° image ([10258.tif](http://demonlj.f3322.net:8588/s/J5afcomN9kPFsdq))
the axis = 992.5

then using the code to reconstruc
`tofu tomo --axis 992.5 --angle 0.700 --sinograms="./*.tif" --output="./ufo/slices-%05i.tif`
but I got confused slices like this
![slices-00006](https://user-images.githubusercontent.com/1272742/64909130-c41fbc80-d73a-11e9-95fc-478c3c6c3ed0.jpg)

Am I doing something wrong?

**Comment by lucito** [comment]
Hi,
not sure about your input data, but could you please try --projections instead of --sinograms ?
Best wishes,
L

**Comment by tfarago** [comment]
Also, `tofu gui` and `tofu tomo` work only with parallel beam data and from the info above it looks like you have cone beam data, please try `tofu reco`

**Comment by Sinapzy** [comment]
-angle-step/-a（which are given in radians!）
