### ISSUE TITLE
ValueError: Namespace ufo not available

### ISSUE THREAD

**Issue by Mary-Cole** [ufo-kit/tofu#91]
Our lab group (Andronowski Lab) has been trying to install ez_ufo for reconstruction of our SRuCT images. We have used ez_ufo successfully for reconstructions at the Canadian Light Source but cannot get it to work on our computers.

It was suggested that we are having an Ubuntu specific error on our dual boot system. Specifically, we were supposed to run the following:

export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
export GI_TYPELIB_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0

However, we now are getting the error ValueError: Namespace Ufo not available when trying to run ez_ufo reconstructions. Tofu gui also gives us this error just by running the command - the tofu gui does not appear. I am attaching screenshots of the readout.

I also tried restarting the computer and running these in a new session and we get the same errors, even without using the commands.

I know tofu gui was working before we made these changes because it did generate tomo images, although it could not execute flatfield.

We are not linux users, so I appreciate your help with figuring out this issue!

**Tofu Gui Error**
![TofuGuiError](https://user-images.githubusercontent.com/59033784/71127948-18af5980-21ba-11ea-80dd-49180b4f5265.png)

**EZ Ufo Error**
![UfoError](https://user-images.githubusercontent.com/59033784/71127949-18af5980-21ba-11ea-9eca-9dc38e2ae491.png)

**Errors Continue After Restart**
![TofuGui_EzUfo_NoCommand](https://user-images.githubusercontent.com/59033784/71127950-18af5980-21ba-11ea-9414-45180eb1bae0.png)

**Comment by Mary-Cole** [comment]
Our lab group (Andronowski Lab) has been trying to install ez_ufo for reconstruction of our SRuCT images. We have used ez_ufo successfully for reconstructions at the Canadian Light Source but cannot get it to work on our computers. 

It was suggested that we are having an Ubuntu specific error on our dual boot system. Specifically, we were supposed to run the following: 

export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
export GI_TYPELIB_PATH=/usr/lib/x86_64-linux-gnu/girepository-1.0

However, we now are getting the error ValueError: Namespace Ufo not available when trying to run ez_ufo reconstructions. Tofu gui also gives us this error just by running the command - the tofu gui does not appear. I am attaching screenshots of the readout. 

I also tried restarting the computer and running these in a new session and we get the same errors, even without using the commands.

I know tofu gui was working before we made these changes because it did generate tomo images, although it could not execute flatfield.

We are not linux users, so I appreciate your help with figuring out this issue!

**Tofu Gui Error**
![TofuGuiError](https://user-images.githubusercontent.com/59033784/71127857-db4acc00-21b9-11ea-8520-4140e927e40d.png)

**Ez Ufo Error**
![UfoError](https://user-images.githubusercontent.com/59033784/71127858-db4acc00-21b9-11ea-9726-72571d4e42eb.png)

**Errors Continue After Restart**
![TofuGui_EzUfo_NoCommand](https://user-images.githubusercontent.com/59033784/71127859-dbe36280-21b9-11ea-9792-d5f20fc9962d.png)

**Comment by milkdrop** [comment]
I do not know Ubuntu version, but there is some more information:
installation from sources to typical Ubuntu directories
ls /usr/include | grep ufo
ufo-0
ls /usr/lib/x86_64-linux-gnu/libufo.so
/usr/lib/x86_64-linux-gnu/libufo.so
ls /usr/lib/x86_64-linux-gnu/ufo/libufofilter
executables are there:
~/ufo-install/tofu$ which tofu
/usr/local/bin/tofu
foote@andronolab-ubuntu:~/ufo-install/tofu$ which ufo-launch
/usr/local/bin/ufo-launch
all prerequisite packages/dependencies mentioned in the "How to install" section in the readthedocs have been installed.

Interestingly enough when ufo/ufo-filter have been installed with apt this problem with gi did not occur. 

On a side note, are you planning to update repositories in the nearest future? In particular on Ubuntu it is so very easy to install opencl and ufo with apt, but unfortunately currently available ufo-filters package is not synchronized with the latest tofu.

Cheers,
Sergei.

**Comment by Mary-Cole** [comment]
Hi Sergei, 

Thank you for continuing to help us with this issue. This doesn't appear to have fixed the issue as we still get the same errors when running ez_ufo or calling tofu gui. 

![NamespaceError](https://user-images.githubusercontent.com/59033784/71685029-255cb180-2d65-11ea-9123-89b39aac5aec.PNG)

It is possible that our files are not in the correct location. When I run "ls /usr/lib/x86_64-linux-gnu/ufo/libufofilter" I get "No such file or directory". All of the filter files are in "ls /usr/lib/x86_64-linux-gnu/ufo" as you can see here: 

![NewCommands](https://user-images.githubusercontent.com/59033784/71684987-0f4ef100-2d65-11ea-91cb-8029137e39da.PNG)

Also, as you can see above, I wasn't successful at getting a response to the ufo-launch commands. There are actually ufo-launch commands scattered around our folders, so potentially we have them in the wrong location.

![UfoLaunchLocations](https://user-images.githubusercontent.com/59033784/71685012-1c6be000-2d65-11ea-8d69-6d2a539f24df.PNG)


I think that the problem is with our Ubuntu dual boot. We would like to start over and try a clean install of Linux to match the exact distribution you are using at CLS. Do you know what specific version we should use? This will hopefully allow us to replicate the CLS settings. 

Thank you!

Sincerely,
Mary Beth

**Comment by ldorofeeva** [comment]
Happy new year!

ufo-launch responds OK as far as I can see. Dual-boot should not be a problem. 
We have CentOS7 at CLS. If you install it I'll send you detailed list of steps describing installation of UFO. But first, please let me get in touch with guys from USASK - an IT guy there managed to configure everything fine about a month ago. I'll ask them how he solved that gi problem. 

SErgei.

**Comment by Mary-Cole** [comment]
Hi Sergei, 

Thank you! Can we go ahead and install CentOS7 as our dual boot while we wait for the settings from USASK? Are there any other specifications we need for the basic dual boot of Linux with Windows 10? 

Sincerely, 
Mary Beth

**Comment by tfarago** [comment]
Hi all, has everything been resolved and can this issue be closed?

**Comment by li-xinshan** [comment]
Hi, I would like to know the detailed installation steps of centos 7, can you please tell me

**Comment by tfarago** [comment]
You need to install [ufo](https://ufo-core.readthedocs.io/en/latest/install/linux.html#opensuse-and-centos7) and then tofu with its requirements by `pip3 install -r requirements-flow.txt` followed by `python3 setup.py install`.
